### ISSUE TITLE
small typing errors

### ISSUE THREAD

**Issue by PKHG** [ipython-books/cookbook-2nd#3]
Hallo some1 or two weeks ago , januari 2019I download all and am very content what you (?) did.
I found a small error in  6.1. Using matplotlib styles
matplotlib is imported as mpl but a few sections later 
matplotlib  was used in place of mpl  ==>missing package 
with a consequence of a missing () a bit later

Greets (a new beginner but very enthousiast about it)
PKHG = Peter K.H. Gragert

**Comment by rossant** [comment]
thanks @PKHG for the bug report! fixed.
closed by 00d6eb1
