### ISSUE TITLE
Binder not working

### ISSUE THREAD

**Issue by worthy7** [ipython-books/cookbook-2nd#5]
Hi there, it seems the Binder button for the notebooks isn't working:

> 
> Step 41/51 : RUN conda env update -p ${NB_PYTHON_PREFIX} -f "environment.yml" && conda clean --all -f -y && conda list -p ${NB_PYTHON_PREFIX}
>  ---> Running in 9349de55aa95
> Collecting package metadata (repodata.json): ...working... done
> Solving environment: ...working... failed
> 
> ResolvePackageNotFound:
>   - pyproj==1.9.5.1=py36_0
>   - holoviews==1.9.0=py36h01658e4_0
>   - cudatoolkit==8.0=3
>   - util-linux==2.21=0
>   - proj4==4.9.3=5
>   - libiconv==1.15=0
>   - geos==3.6.2=1
>   - libdap4==3.19.2=1
>   - libpq==9.5.4=0
>   - libgdal==2.0.0=1
> 
> Removing intermediate container 9349de55aa95
> The command '/bin/sh -c conda env update -p ${NB_PYTHON_PREFIX} -f "environment.yml" && conda clean --all -f -y && conda list -p ${NB_PYTHON_PREFIX}' returned a non-zero code: 1

**Comment by rossant** [comment]
Thanks for the bug report. I updated the `environment.yml` file, checking now if this fixes it

**Comment by rossant** [comment]
Seems to work! Please reopen if there is any further issue.
